### ISSUE TITLE
`import` is better than `include`

### ISSUE THREAD

**Issue by tenntenn** [budougumi0617/layer#3]
I think word of `import` is prefer than `include` in below cases.
https://github.com/budougumi0617/layer/blob/master/analyzer.go#L81

**Comment by budougumi0617** [comment]
[memo] line shifted.
https://github.com/budougumi0617/layer/blob/b2364381331293d6a70e5ba827c6ad74e0baeabc/analyzer.go#L88

**Comment by budougumi0617** [comment]
Thanks good advise! I changed it word!
